<?php
/**
 * OVH Module Configuration Example
 *
 * This file provides configuration examples and API credential setup instructions
 * Copy this file to config.php and fill in your OVH API credentials
 */

// DO NOT EDIT THIS FILE - Copy to config.php instead

return [
    /**
     * OVH API Endpoints
     *
     * Choose the appropriate endpoint for your region:
     * - 'ovh-eu' for Europe (https://eu.api.ovh.com)
     * - 'ovh-ca' for Canada (https://ca.api.ovh.com)
     * - 'ovh-us' for United States (https://api.ovhcloud.com)
     */
    'endpoint' => 'ovh-eu',

    /**
     * OVH API Credentials
     *
     * To obtain these credentials:
     *
     * 1. Go to: https://eu.api.ovh.com/createApp/ (or your region's equivalent)
     *    - EU: https://eu.api.ovh.com/createApp/
     *    - CA: https://ca.api.ovh.com/createApp/
     *    - US: https://api.ovhcloud.com/createApp/
     *
     * 2. Fill in:
     *    - Application name: "WHMCS OVH Module"
     *    - Application description: "Server provisioning and management"
     *
     * 3. You will receive:
     *    - Application Key (AK)
     *    - Application Secret (AS)
     *
     * 4. Generate a Consumer Key:
     *    Visit: https://eu.api.ovh.com/createToken/ (or your region's equivalent)
     *
     *    Required API Rights (set validity to "Unlimited"):
     *
     *    For Dedicated Servers:
     *    - GET    /dedicated/server
     *    - GET    /dedicated/server/*
     *    - POST   /dedicated/server/*
     *    - PUT    /dedicated/server/*
     *    - DELETE /dedicated/server/*
     *
     *    For VPS:
     *    - GET    /vps
     *    - GET    /vps/*
     *    - POST   /vps/*
     *    - PUT    /vps/*
     *    - DELETE /vps/*
     *
     *    For Public Cloud:
     *    - GET    /cloud/project
     *    - GET    /cloud/project/*
     *    - POST   /cloud/project/*
     *    - PUT    /cloud/project/*
     *    - DELETE /cloud/project/*
     *
     *    For IP Management:
     *    - GET    /ip
     *    - GET    /ip/*
     *    - POST   /ip/*
     *    - PUT    /ip/*
     *
     *    For Account Info:
     *    - GET    /me
     *    - GET    /me/*
     *
     * 5. After submitting, you'll receive your Consumer Key (CK)
     */
    'application_key' => 'YOUR_APPLICATION_KEY',
    'application_secret' => 'YOUR_APPLICATION_SECRET',
    'consumer_key' => 'YOUR_CONSUMER_KEY',

    /**
     * Default Service Settings
     */
    'defaults' => [
        'operating_system' => 'ubuntu2204_64',
        'control_panel' => 'none',
        'enable_monitoring' => true,
        'enable_backup' => false,
    ],

    /**
     * Supported Operating Systems
     *
     * Map of OS identifiers to display names
     * These should match the template names available in your OVH account
     */
    'operating_systems' => [
        // Debian
        'debian11_64' => 'Debian 11 (Bullseye) 64-bit',
        'debian12_64' => 'Debian 12 (Bookworm) 64-bit',

        // Ubuntu
        'ubuntu2004_64' => 'Ubuntu 20.04 LTS (Focal) 64-bit',
        'ubuntu2204_64' => 'Ubuntu 22.04 LTS (Jammy) 64-bit',
        'ubuntu2404_64' => 'Ubuntu 24.04 LTS (Noble) 64-bit',

        // CentOS / AlmaLinux / Rocky
        'centos7_64' => 'CentOS 7 64-bit',
        'centos8_64' => 'CentOS Stream 8 64-bit',
        'centos9_64' => 'CentOS Stream 9 64-bit',
        'almalinux8_64' => 'AlmaLinux 8 64-bit',
        'almalinux9_64' => 'AlmaLinux 9 64-bit',
        'rockylinux8_64' => 'Rocky Linux 8 64-bit',
        'rockylinux9_64' => 'Rocky Linux 9 64-bit',

        // Fedora
        'fedora38_64' => 'Fedora 38 64-bit',
        'fedora39_64' => 'Fedora 39 64-bit',

        // Windows
        'windows2019_64' => 'Windows Server 2019 Standard 64-bit',
        'windows2022_64' => 'Windows Server 2022 Standard 64-bit',
    ],

    /**
     * Service Types
     */
    'service_types' => [
        'dedicated' => 'Dedicated Server',
        'vps' => 'Virtual Private Server (VPS)',
        'cloud' => 'Public Cloud Instance',
    ],

    /**
     * Logging Configuration
     */
    'logging' => [
        'enabled' => true,
        'log_api_calls' => true,
        'log_level' => 'info', // debug, info, warning, error
    ],

    /**
     * Timeout Settings (in seconds)
     */
    'timeouts' => [
        'api_timeout' => 30,
        'connection_timeout' => 10,
    ],

    /**
     * Feature Flags
     */
    'features' => [
        'auto_monitoring' => true,
        'auto_backup' => false,
        'ipmi_access' => true,
        'rescue_mode' => true,
        'os_reinstall' => true,
        'bandwidth_graphs' => false,
    ],

    /**
     * OVH Manager URLs
     */
    'manager_urls' => [
        'ovh-eu' => 'https://www.ovh.com/manager/',
        'ovh-ca' => 'https://ca.ovh.com/manager/',
        'ovh-us' => 'https://us.ovhcloud.com/manager/',
    ],

    /**
     * API Rate Limiting
     *
     * OVH has rate limits on their API:
     * - Dedicated: 1000 calls/hour
     * - VPS: 500 calls/hour
     * - Public Cloud: 2000 calls/hour
     */
    'rate_limits' => [
        'enabled' => true,
        'max_calls_per_hour' => 500,
    ],

    /**
     * Webhook Configuration (Optional)
     *
     * Set up webhooks to receive notifications from OVH
     */
    'webhooks' => [
        'enabled' => false,
        'secret' => 'your_webhook_secret',
        'url' => 'https://your-whmcs-domain.com/modules/servers/ovh/webhook.php',
    ],
];

/**
 * Quick Setup Guide:
 *
 * 1. Copy this file to config.php
 * 2. Get OVH API credentials from https://eu.api.ovh.com/createApp/
 * 3. Generate Consumer Key with appropriate permissions
 * 4. Update application_key, application_secret, and consumer_key above
 * 5. Configure your products in WHMCS to use the OVH module
 * 6. Set the Service Name/ID for each product (e.g., ns123456.ip-1-2-3.eu)
 * 7. Test the connection using WHMCS admin panel
 *
 * WHMCS Product Configuration:
 *
 * 1. Go to: Setup > Products/Services > Products/Services
 * 2. Create/Edit a product
 * 3. Module Settings tab:
 *    - Module: OVH Servers
 *    - Endpoint: Select your region (ovh-eu, ovh-ca, or ovh-us)
 *    - Application Key: Your AK from OVH
 *    - Application Secret: Your AS from OVH
 *    - Consumer Key: Your CK from OVH
 *    - Service Type: Choose dedicated, vps, or cloud
 *    - Service Name/ID: The OVH service identifier
 *    - Operating System: Default OS for new installations
 *    - Control Panel: Optional control panel
 *    - Enable Monitoring: Yes/No
 *    - Enable Backup: Yes/No
 *
 * Troubleshooting:
 *
 * - Check WHMCS Activity Log for API errors
 * - Verify Consumer Key has correct permissions
 * - Ensure Service Name/ID matches your OVH service
 * - Test API connection from WHMCS admin
 * - Check OVH API status: https://status.ovh.com/
 *
 * Support:
 *
 * - OVH API Documentation: https://api.ovh.com/
 * - OVH API Console: https://api.ovh.com/console/
 * - WHMCS Module Development: https://developers.whmcs.com/
 */
